
CREATE TABLE diretor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    data_nascimento DATE,
    criado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL
);


CREATE TABLE filme (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    genero VARCHAR(50) NOT NULL,
    ano_lancamento DATE,
    avaliacao INTEGER,
    assistido BOOLEAN NOT NULL DEFAULT FALSE,
    favorito BOOLEAN NOT NULL DEFAULT FALSE,
    diretor_id BIGINT,
    criado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_filme_diretor FOREIGN KEY (diretor_id) REFERENCES diretor (id)
);


CREATE TABLE lista (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL
);


CREATE TABLE lista_filme (
    lista_id BIGINT NOT NULL,
    filme_id BIGINT NOT NULL,
    PRIMARY KEY (lista_id, filme_id),
    CONSTRAINT fk_listafilme_lista FOREIGN KEY (lista_id) REFERENCES lista (id) ON DELETE CASCADE,
    CONSTRAINT fk_listafilme_filme FOREIGN KEY (filme_id) REFERENCES filme (id) ON DELETE CASCADE
);